In [1]:
import pandas as pd
from sklearn.ensemble import AdaBoostClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
import numpy as np 

In [2]:
# Metric printing 
def metrics(ytrue,ypred):
    print(confusion_matrix(ytrue,ypred))
    print("the accuracy is ",accuracy_score(ytrue,ypred))
    #print("the precision is ",precision_score(ytrue,ypred))
    #print("the recall is ",recall_score(ytrue,ypred))
    print(classification_report(ytrue, ypred))
    return accuracy_score(ytrue,ypred)#, precision_score(ytrue,ypred), recall_score(ytrue,ypred)

In [3]:
link = './accident dataset/new york accidents preprocessed.csv'
data = pd.read_csv(link)

In [4]:
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.3
)

In [7]:
adaboost = AdaBoostClassifier(n_estimators=50)

In [8]:
adaboost.fit(xtrain, ytrain)

AdaBoostClassifier()

In [9]:
trainpred = adaboost.predict(xtrain)
metrics(ytrain, trainpred)

[[    29    713    219      0]
 [   145 241981  12149    977]
 [    18  22504  39274    102]
 [     5   9188    612   1274]]
the accuracy is  0.8583432060512166
              precision    recall  f1-score   support

           1       0.15      0.03      0.05       961
           2       0.88      0.95      0.91    255252
           3       0.75      0.63      0.69     61898
           4       0.54      0.11      0.19     11079

    accuracy                           0.86    329190
   macro avg       0.58      0.43      0.46    329190
weighted avg       0.84      0.86      0.84    329190


0.8583432060512166

In [10]:
ypred = adaboost.predict(xtest)
metrics(ytest, ypred)

[[    19    349     80      0]
 [    77 104009   5169    420]
 [     6   9610  16661     37]
 [     4   3867    267    507]]
the accuracy is  0.859046511957585
              precision    recall  f1-score   support

           1       0.18      0.04      0.07       448
           2       0.88      0.95      0.91    109675
           3       0.75      0.63      0.69     26314
           4       0.53      0.11      0.18      4645

    accuracy                           0.86    141082
   macro avg       0.58      0.43      0.46    141082
weighted avg       0.84      0.86      0.85    141082


0.859046511957585