In [3]:
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
import numpy as np 

In [2]:
# Metric printing 
def metrics(ytrue,ypred):
    print(confusion_matrix(ytrue,ypred))
    print("the accuracy is ",accuracy_score(ytrue,ypred))
    #print("the precision is ",precision_score(ytrue,ypred))
    #print("the recall is ",recall_score(ytrue,ypred))
    print(classification_report(ytrue, ypred))
    return accuracy_score(ytrue,ypred)#, precision_score(ytrue,ypred), recall_score(ytrue,ypred)

In [9]:
link = './accident dataset/new york accidents preprocessed.csv'
data = pd.read_csv(link)

In [10]:
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.2
)

In [6]:
param_grid = {
    'n_neighbors':[4,5,7,9,10], 
    'weights':['uniform', 'distance']
}
best = GridSearchCV(
    KNeighborsClassifier(n_jobs= -1), 
    param_grid=param_grid, 
    n_jobs=-1
)

getting best features according to Random forest

In [11]:
xtrain = xtrain[['Zipcode', 'Distance(mi)', 'Street', 'Start_Lat','Start_Lng']]
xtest  = xtest[['Zipcode', 'Distance(mi)', 'Street', 'Start_Lat','Start_Lng']]

In [21]:
best.fit(xtrain, ytrain)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be remo

KeyboardInterrupt: 

In [10]:
best.best_params_

{'n_neighbors': 9, 'weights': 'uniform'}

In [12]:
n_neighbors, weights = best.best_params_.values()

In [15]:
weights

'uniform'

In [13]:
knn = KNeighborsClassifier(
    n_neighbors= 9,#n_neighbors,
    #weights= weights,
    n_jobs = -1
)

In [14]:
knn.fit(xtrain, ytrain)

KNeighborsClassifier(n_jobs=-1, n_neighbors=9)

In [15]:
ypred = knn.predict(xtest)

In [16]:
metrics(ytest, ypred)

[[    5   219    51     0]
 [    6 68828  3912   269]
 [    6  5145 12384    39]
 [    0  2550   188   453]]
the accuracy is  0.868321726649301
              precision    recall  f1-score   support

           1       0.29      0.02      0.03       275
           2       0.90      0.94      0.92     73015
           3       0.75      0.70      0.73     17574
           4       0.60      0.14      0.23      3191

    accuracy                           0.87     94055
   macro avg       0.63      0.45      0.48     94055
weighted avg       0.86      0.87      0.86     94055


0.868321726649301

# KNN on data with temp clusters

In [26]:
link = './accident dataset/new york accident minimeans clustered.csv'
data = pd.read_csv(link)
data = data.drop('TimeTaken', axis=1)
data.head()

Severity  Start_Lat  Start_Lng  Distance(mi)    Street   Zipcode  Amenity  \
0         2  -0.477042   0.206319     -0.364533 -0.004402  0.673132        0   
1         3  -0.113118   0.256402     -0.364533  0.527205  2.825723        0   
2         3  -0.133706   0.263927      0.951761  0.994872  0.853023        0   
3         3  -0.238482   0.592595      0.241380  0.002717 -0.190761        0   
4         3   0.138075   0.681182     -0.364533  0.605621  1.187742        0   

   Bump  Crossing  Give_Way  ...  Station  Stop  Traffic_Calming  \
0     0         0         0  ...        0     0                0   
1     0         0         0  ...        0     0                0   
2     0         0         0  ...        0     0                0   
3     0         0         0  ...        0     0                0   
4     0         0         0  ...        0     0                0   

   Traffic_Signal  Turning_Loop  Sunrise_Sunset  Civil_Twilight  \
0               1             0               1               0   
1               0             0               0               0   
2               0             0               0               0   
3               0             0               0               0   
4               0             0               0               0   

   Nautical_Twilight  Astronomical_Twilight  tempClusters  
0                  0                      0     -0.011049  
1                  0                      0      1.473246  
2                  0                      0      1.613054  
3                  0                      0      1.489703  
4                  0                      0      1.357445  

[5 rows x 24 columns]

In [27]:
data = data[['Zipcode', 'Distance(mi)', 'Street', 'Start_Lat','Start_Lng','tempClusters','Severity']]
data.head()

Zipcode  Distance(mi)    Street  Start_Lat  Start_Lng  tempClusters  \
0  0.673132     -0.364533 -0.004402  -0.477042   0.206319     -0.011049   
1  2.825723     -0.364533  0.527205  -0.113118   0.256402      1.473246   
2  0.853023      0.951761  0.994872  -0.133706   0.263927      1.613054   
3 -0.190761      0.241380  0.002717  -0.238482   0.592595      1.489703   
4  1.187742     -0.364533  0.605621   0.138075   0.681182      1.357445   

   Severity  
0         2  
1         3  
2         3  
3         3  
4         3

In [28]:
#data = data.drop('TimeTaken',axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.2
)

In [29]:
knn = KNeighborsClassifier(
    n_neighbors=9, #n_neighbors
    #weights=weights
    n_jobs=-1,
)

In [30]:
knn.fit(xtrain, ytrain)

KNeighborsClassifier(n_jobs=-1, n_neighbors=9)

In [31]:
ypred = knn.predict(xtest)

In [32]:
metrics(ytest, ypred)

[[    3   259    21     0]
 [    5 68690  4004   200]
 [    2  6003 11563    59]
 [    0  2446   336   464]]
the accuracy is  0.8582212535218755
              precision    recall  f1-score   support

           1       0.30      0.01      0.02       283
           2       0.89      0.94      0.91     72899
           3       0.73      0.66      0.69     17627
           4       0.64      0.14      0.23      3246

    accuracy                           0.86     94055
   macro avg       0.64      0.44      0.46     94055
weighted avg       0.85      0.86      0.85     94055


0.8582212535218755