In [24]:
import pandas as pd
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
import numpy as np 

In [2]:
# Metric printing 
def metrics(ytrue,ypred):
    print(confusion_matrix(ytrue,ypred))
    print("the accuracy is ",accuracy_score(ytrue,ypred))
    #print("the precision is ",precision_score(ytrue,ypred))
    #print("the recall is ",recall_score(ytrue,ypred))
    print(classification_report(ytrue, ypred))
    return accuracy_score(ytrue,ypred)#, precision_score(ytrue,ypred), recall_score(ytrue,ypred)

In [3]:
link = './accident dataset/new york accidents preprocessed.csv'
data = pd.read_csv(link)


In [19]:
#data = data.drop('TimeTaken',axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.2
)

In [20]:
xtrain = xtrain[['Amenity', 'Bump', 'Crossing','Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station','Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop','Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight','Astronomical_Twilight']]
xtest = xtest[['Amenity', 'Bump', 'Crossing','Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station','Stop', 'Traffic_Calming', 'Traffic_Signal', 'Turning_Loop','Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight','Astronomical_Twilight']]

In [29]:
naive = MultinomialNB()
naive.fit(xtrain, ytrain)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: Future

MultinomialNB()

In [30]:
xtrain

Amenity  Bump  Crossing  Give_Way  Junction  No_Exit  Railway  \
114795        0     0         0         0         0        0        0   
298611        0     0         0         0         0        0        0   
276897        0     0         0         0         0        0        0   
361185        0     0         0         0         0        0        0   
111784        0     0         0         0         1        0        0   
...         ...   ...       ...       ...       ...      ...      ...   
315208        0     0         0         0         0        0        0   
177873        0     0         0         0         0        0        0   
160207        1     0         0         0         0        0        0   
298493        0     0         0         0         0        0        0   
132159        1     0         0         0         0        0        1   

        Roundabout  Station  Stop  Traffic_Calming  Traffic_Signal  \
114795           0        0     0                0               0   
298611           0        0     0                0               0   
276897           0        0     0                0               0   
361185           0        0     0                0               1   
111784           0        0     1                0               0   
...            ...      ...   ...              ...             ...   
315208           0        0     0                0               0   
177873           0        0     0                0               0   
160207           0        1     0                0               0   
298493           0        0     0                0               0   
132159           0        1     0                0               1   

        Turning_Loop  Sunrise_Sunset  Civil_Twilight  Nautical_Twilight  \
114795             0               0               0                  0   
298611             0               0               0                  0   
276897             0               0               0                  0   
361185             0               0               0                  0   
111784             0               0               0                  0   
...              ...             ...             ...                ...   
315208             0               0               0                  0   
177873             0               1               1                  1   
160207             0               0               0                  0   
298493             0               0               0                  0   
132159             0               0               0                  0   

        Astronomical_Twilight  
114795                      0  
298611                      0  
276897                      0  
361185                      0  
111784                      0  
...                       ...  
315208                      0  
177873                      1  
160207                      0  
298493                      0  
132159                      0  

[376217 rows x 17 columns]

In [31]:
trainpred = naive.predict(xtrain)
metrics(ytrain, trainpred)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: Future

[[     0   1134      0      0]
 [     0 291866    136      0]
 [     0  70450     66      0]
 [     0  12557      8      0]]
the accuracy is  0.7759670615628746
              precision    recall  f1-score   support

           1       0.00      0.00      0.00      1134
           2       0.78      1.00      0.87    292002
           3       0.31      0.00      0.00     70516
           4       0.00      0.00      0.00     12565

    accuracy                           0.78    376217
   macro avg       0.27      0.25      0.22    376217
weighted avg       0.66      0.78      0.68    376217


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/Environment

0.7759670615628746

In [32]:
ypred = naive.predict(xtest)
metrics(ytest, ypred)

[[    0   275     0     0]
 [    0 72892    33     0]
 [    0 17679    17     0]
 [    0  3157     2     0]]
the accuracy is  0.7751741002604858
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       275
           2       0.78      1.00      0.87     72925
           3       0.33      0.00      0.00     17696
           4       0.00      0.00      0.00      3159

    accuracy                           0.78     94055
   macro avg       0.28      0.25      0.22     94055
weighted avg       0.66      0.78      0.68     94055


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: Future

0.7751741002604858