In [2]:
import numpy as np
import pandas as pd 
#import tensorflow as tf 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [1]:
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers.legacy import Adam, SGD
from tensorflow.keras.models import Sequential 
from tensorflow.keras import metrics 

In [80]:
# Metric printing 
def metric_analysis(ytrue,ypred):
    print(confusion_matrix(ytrue,ypred))
    print("the accuracy is ",accuracy_score(ytrue,ypred))
    #print("the precision is ",precision_score(ytrue,ypred))
    #print("the recall is ",recall_score(ytrue,ypred))
    print(classification_report(ytrue, ypred))
    return accuracy_score(ytrue,ypred)#, precision_score(ytrue,ypred), recall_score(ytrue,ypred)

In [4]:
link = './accident dataset/new york accidents preprocessed.csv'
data = pd.read_csv(link)

In [5]:
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.3
)

according to random forest the important features were 'Zipcode', 'Distance(mi)', 'TimeTaken', 'Street', 'Start_Lat','Start_Lng',

xtrain = xtrain[['Zipcode', 'Distance(mi)', 'TimeTaken', 'Street', 'Start_Lat','Start_Lng']]
xtest  = xtest[['Zipcode', 'Distance(mi)', 'TimeTaken', 'Street', 'Start_Lat','Start_Lng']]

In [6]:
xtrain.shape

(329190, 29)

In [67]:
model = Sequential()
model.add(
    Dense(
        units= 50, 
        activation='sigmoid', 
        input_shape= (29,)
    )
)
model.add(Dropout(0.2))
model.add(Dense(
    units=25,
    activation='sigmoid',
))
model.add(Dropout(0.1))
model.add(Dense(
    units = 4, 
    activation='softmax'
)) 

In [68]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_25 (Dense)            (None, 50)                1500      
                                                                 
 dropout_18 (Dropout)        (None, 50)                0         
                                                                 
 dense_26 (Dense)            (None, 25)                1275      
                                                                 
 dropout_19 (Dropout)        (None, 25)                0         
                                                                 
 dense_27 (Dense)            (None, 4)                 104       
                                                                 
Total params: 2879 (11.25 KB)
Trainable params: 2879 (11.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [69]:
opt = Adam(learning_rate = 0.005)
model.compile(optimizer=opt, loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [70]:
#metrics.Precision(), metrics.Recall(),

In [71]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_25 (Dense)            (None, 50)                1500      
                                                                 
 dropout_18 (Dropout)        (None, 50)                0         
                                                                 
 dense_26 (Dense)            (None, 25)                1275      
                                                                 
 dropout_19 (Dropout)        (None, 25)                0         
                                                                 
 dense_27 (Dense)            (None, 4)                 104       
                                                                 
Total params: 2879 (11.25 KB)
Trainable params: 2879 (11.25 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [73]:
model.fit(xtrain,ytrain, epochs=3)

Epoch 1/3
10288/10288 [==============================] - 60s 6ms/step - loss: 0.3257 - sparse_categorical_accuracy: 0.8451
Epoch 2/3
10288/10288 [==============================] - 58s 6ms/step - loss: 0.3416 - sparse_categorical_accuracy: 0.8353
Epoch 3/3
10288/10288 [==============================] - 57s 5ms/step - loss: 0.3537 - sparse_categorical_accuracy: 0.8350


In [74]:
model.evaluate(xtrain,ytrain)

10288/10288 [==============================] - 36s 3ms/step - loss: 0.3900 - sparse_categorical_accuracy: 0.8210


[0.39004820585250854, 0.8209757208824158]

In [64]:
model.evaluate(xtest, ytest)

4409/4409 [==============================] - 16s 4ms/step - loss: 0.3311 - sparse_categorical_accuracy: 0.8457


[0.3310743570327759, 0.8457351326942444]

In [75]:
trainpred = model.predict(xtrain)

10288/10288 [==============================] - 13s 1ms/step


In [81]:
metric_analysis(ytrain, trainpred.argmax(axis=1))

[[     0    992      3      0]
 [     0 253659   1813      0]
 [     0  45181  16598      0]
 [     0  10899     45      0]]
the accuracy is  0.8209757283028039
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       995
           2       0.82      0.99      0.90    255472
           3       0.90      0.27      0.41     61779
           4       0.00      0.00      0.00     10944

    accuracy                           0.82    329190
   macro avg       0.43      0.32      0.33    329190
weighted avg       0.80      0.82      0.77    329190


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

0.8209757283028039

In [82]:
ypred = model.predict(xtest)
ypred

4409/4409 [==============================] - 6s 1ms/step


array([[4.6338502e-09, 4.3901009e-03, 9.1168064e-01, 8.3929293e-02],
       [4.6391055e-09, 4.4015227e-03, 9.1477817e-01, 8.0820352e-02],
       [4.6335979e-09, 4.3984437e-03, 9.1497558e-01, 8.0625914e-02],
       ...,
       [4.6371902e-09, 4.4005103e-03, 9.1484696e-01, 8.0752470e-02],
       [2.9975471e-09, 2.6107873e-03, 5.1845372e-01, 4.7893554e-01],
       [4.6392503e-09, 4.4011222e-03, 9.1458338e-01, 8.1015497e-02]],
      dtype=float32)

In [84]:
metric_analysis(ytest, ypred.argmax(axis=1))

[[     0    413      1      0]
 [     0 108683    772      0]
 [     0  19343   7090      0]
 [     0   4771      9      0]]
the accuracy is  0.8206078734353072
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       414
           2       0.82      0.99      0.90    109455
           3       0.90      0.27      0.41     26433
           4       0.00      0.00      0.00      4780

    accuracy                           0.82    141082
   macro avg       0.43      0.32      0.33    141082
weighted avg       0.80      0.82      0.77    141082


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(av

0.8206078734353072