In [1]:
import pandas as pd 
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
from sklearn.neighbors import KNeighborsClassifier
import numpy as np 

In [35]:
# Metric printing 
def metrics(ytrue,ypred):
    print(confusion_matrix(ytrue,ypred))
    print("the accuracy is ",accuracy_score(ytrue,ypred))
    #print("the precision is ",precision_score(ytrue,ypred))
    #print("the recall is ",recall_score(ytrue,ypred))
    print(classification_report(ytrue, ypred))
    return accuracy_score(ytrue,ypred)#, precision_score(ytrue,ypred), recall_score(ytrue,ypred)

In [19]:
link = './accident dataset/new york accidents preprocessed.csv'
data = pd.read_csv(link)


In [20]:
data = data.drop('TimeTaken', axis=1)

train = data[:329191]
test = data[329191:]

train.shape

test.shape

ytrain = train.Severity
xtrain = train.drop('Severity', axis=1)
ytest = test.Severity
xtest = test.drop('Severity', axis=1)

In [21]:
#data = data.drop('TimeTaken',axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.2
)

In [6]:
'''param_grid = {
    'n_estimators':[50,100,150],
    'max_depth':[None,4,10,12],
    'max_leaf_nodes':[None,4,5,6,7,10],
    'max_features':[None,10,20,30,40],
    'criterion':['gini','entropy']
}
best = GridSearchCV(
    RandomForestClassifier(),
    param_grid=param_grid,
    n_jobs=-1
)'''

"param_grid = {\n    'n_estimators':[50,100,150],\n    'max_depth':[None,6,7,8,9,10,12],\n    'max_leaf_nodes':[None,4,5,6,7,10],\n    'max_features':[None,10,20,30,40],\n    'criterion':['gini','entropy']\n}\nbest = GridSearchCV(\n    RandomForestClassifier(),\n    param_grid=param_grid,\n    n_jobs=-1\n)"

In [7]:
#best.fit(xtrain, ytrain)

In [22]:
rlf = RandomForestClassifier(
    n_estimators=100,
    criterion='gini',
    n_jobs=-1
)

In [23]:
rlf.fit(xtrain, ytrain)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: Future

RandomForestClassifier(n_jobs=-1)

In [24]:
ytrainpred = rlf.predict(xtrain)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


In [25]:
metrics(ytrain, ytrainpred)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be remo

[[  1133      1      0      0]
 [     0 291912      0     16]
 [     0      5  70586      2]
 [     0    114      1  12447]]
the accuracy is  0.9996305323789196
              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1134
           2       1.00      1.00      1.00    291928
           3       1.00      1.00      1.00     70593
           4       1.00      0.99      0.99     12562

    accuracy                           1.00    376217
   macro avg       1.00      1.00      1.00    376217
weighted avg       1.00      1.00      1.00    376217


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be remo

0.9996305323789196

In [26]:
ypred = rlf.predict(xtest)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


In [27]:
metrics(ytest, ypred)

[[   48   203    24     0]
 [    2 70185  2555   257]
 [    1  4543 13020    55]
 [    0  2244   146   772]]
the accuracy is  0.8933602679283398
              precision    recall  f1-score   support

           1       0.94      0.17      0.29       275
           2       0.91      0.96      0.93     72999
           3       0.83      0.74      0.78     17619
           4       0.71      0.24      0.36      3162

    accuracy                           0.89     94055
   macro avg       0.85      0.53      0.59     94055
weighted avg       0.89      0.89      0.88     94055


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be remo

0.8933602679283398

In [29]:
print(classification_report(ytest, ypred))

              precision    recall  f1-score   support

           1       0.92      0.22      0.36       271
           2       0.92      0.96      0.94     73174
           3       0.84      0.76      0.79     17446
           4       0.77      0.30      0.43      3164

    accuracy                           0.90     94055
   macro avg       0.86      0.56      0.63     94055
weighted avg       0.90      0.90      0.89     94055


In [15]:
data.columns[1:][np.argsort(rlf.feature_importances_)[::-1]]

Index(['Zipcode', 'Distance(mi)', 'TimeTaken', 'Street', 'Start_Lat',
       'Start_Lng', 'Weather_Condition', 'Wind_Direction', 'Pressure(in)',
       'Temperature(F)', 'Humidity(%)', 'Visibility(mi)', 'Traffic_Signal',
       'Junction', 'Sunrise_Sunset', 'Crossing', 'Astronomical_Twilight',
       'Civil_Twilight', 'Nautical_Twilight', 'Stop', 'Amenity', 'Station',
       'Give_Way', 'Railway', 'No_Exit', 'Traffic_Calming', 'Bump',
       'Roundabout', 'Turning_Loop'],
      dtype='object')

Index(['Distance(mi)', 'Zipcode', 'Street', 'Start_Lat', 'Start_Lng',
       'Weather_Condition', 'Wind_Direction', 'Pressure(in)', 'Temperature(F)',
       'Humidity(%)', 'Visibility(mi)', 'Traffic_Signal', 'Junction',
       'Sunrise_Sunset', 'Civil_Twilight', 'Nautical_Twilight',
       'Astronomical_Twilight', 'Crossing', 'Stop', 'Amenity', 'Station',
       'Give_Way', 'Railway', 'No_Exit', 'Traffic_Calming', 'Bump',
       'Roundabout', 'Turning_Loop'],
      dtype='object')

ImportError: cannot import name 'TargetEncoder' from 'sklearn.preprocessing' (/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/preprocessing/__init__.py)

# random forest try 2 with temps clustered

In [37]:
link = './accident dataset/new york accident minimeans clustered.csv'
data = pd.read_csv(link)
data = data.drop('TimeTaken', axis=1)
data.head()

In [5]:
#data = data.drop('TimeTaken',axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.2
)

NameError: name 'data' is not defined

In [39]:
rlf = RandomForestClassifier(
    n_estimators=100, 
    criterion='gini', 
    n_jobs=-1
)
rlf.fit(xtrain, ytrain)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: Future

RandomForestClassifier(n_jobs=-1)

In [40]:
trainpred = rlf.predict(xtrain)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


In [41]:
metrics(ytrain, trainpred)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be remo

[[  1114      3      2      0]
 [     2 291912     98     18]
 [     0     61  70509      7]
 [     0    115      3  12373]]
the accuracy is  0.999178665504217
              precision    recall  f1-score   support

           1       1.00      1.00      1.00      1119
           2       1.00      1.00      1.00    292030
           3       1.00      1.00      1.00     70577
           4       1.00      0.99      0.99     12491

    accuracy                           1.00    376217
   macro avg       1.00      1.00      1.00    376217
weighted avg       1.00      1.00      1.00    376217


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be remo

0.999178665504217

In [42]:
ypred = rlf.predict(xtest)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:767: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if not hasattr(array, "sparse") and array.dtypes.apply(is_sparse).any():
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):


In [43]:
metrics(ytest, ypred)

[[   50   212    27     1]
 [   24 69817  2698   358]
 [    7  4590 12969    69]
 [    4  2247   161   821]]
the accuracy is  0.8894476636010845
              precision    recall  f1-score   support

           1       0.59      0.17      0.27       290
           2       0.91      0.96      0.93     72897
           3       0.82      0.74      0.77     17635
           4       0.66      0.25      0.37      3233

    accuracy                           0.89     94055
   macro avg       0.74      0.53      0.58     94055
weighted avg       0.88      0.89      0.88     94055


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype) or not is_extension_array_dtype(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:605: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(pd_dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/sklearn/utils/validation.py:614: FutureWarning: is_sparse is deprecated and will be remo

0.8894476636010845