In [1]:
import pandas as pd
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report
import numpy as np 
from sklearn.preprocessing import LabelEncoder

In [2]:
# Metric printing 
def metrics(ytrue,ypred):
    print(confusion_matrix(ytrue,ypred))
    print("the accuracy is ",accuracy_score(ytrue,ypred))
    #print("the precision is ",precision_score(ytrue,ypred))
    #print("the recall is ",recall_score(ytrue,ypred))
    print(classification_report(ytrue, ypred))
    return accuracy_score(ytrue,ypred)#, precision_score(ytrue,ypred), recall_score(ytrue,ypred)

In [16]:
link = './accident dataset/new york accidents preprocessed.csv'
data = pd.read_csv(link)

In [17]:
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.3
)

In [18]:
le = LabelEncoder()
le.fit(ytrain.ravel())


LabelEncoder()

In [23]:
le.classes_

array([1, 2, 3, 4])

In [24]:
ytrain =pd.DataFrame(le.transform(ytrain)) 
ytest = pd.DataFrame(le.transform(ytest))

In [25]:
xgb = XGBClassifier(n_jobs=-1)

In [26]:
xgb.fit(xtrain, ytrain)
trainpred = xgb.predict(xtrain)
metrics(ytrain, trainpred)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:299: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:301: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:332: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:323: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. U

[[   398    507     82      1]
 [    15 245995   8920    481]
 [     6  13996  47564    261]
 [     2   6312    466   4184]]
the accuracy is  0.9056806099820772
              precision    recall  f1-score   support

           0       0.95      0.40      0.56       988
           1       0.92      0.96      0.94    255411
           2       0.83      0.77      0.80     61827
           3       0.85      0.38      0.53     10964

    accuracy                           0.91    329190
   macro avg       0.89      0.63      0.71    329190
weighted avg       0.90      0.91      0.90    329190


0.9056806099820772

In [27]:
ypred = xgb.predict(xtest)
metrics(ytest, ypred)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:299: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:301: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:332: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:323: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. U

[[    79    293     49      0]
 [    26 104803   4342    345]
 [    14   6427  19817    127]
 [     1   3027    259   1473]]
the accuracy is  0.8943167803121589
              precision    recall  f1-score   support

           0       0.66      0.19      0.29       421
           1       0.91      0.96      0.94    109516
           2       0.81      0.75      0.78     26385
           3       0.76      0.31      0.44      4760

    accuracy                           0.89    141082
   macro avg       0.79      0.55      0.61    141082
weighted avg       0.89      0.89      0.89    141082


0.8943167803121589

# XGBOOST on clustered data 

In [3]:
link = './accident dataset/new york accident minimeans clustered.csv'
data = pd.read_csv(link)
data = data.drop('TimeTaken', axis=1)
data.head()

Severity  Start_Lat  Start_Lng  Distance(mi)    Street   Zipcode  Amenity  \
0         2  -0.477042   0.206319     -0.364533 -0.004402  0.673132        0   
1         3  -0.113118   0.256402     -0.364533  0.527205  2.825723        0   
2         3  -0.133706   0.263927      0.951761  0.994872  0.853023        0   
3         3  -0.238482   0.592595      0.241380  0.002717 -0.190761        0   
4         3   0.138075   0.681182     -0.364533  0.605621  1.187742        0   

   Bump  Crossing  Give_Way  ...  Station  Stop  Traffic_Calming  \
0     0         0         0  ...        0     0                0   
1     0         0         0  ...        0     0                0   
2     0         0         0  ...        0     0                0   
3     0         0         0  ...        0     0                0   
4     0         0         0  ...        0     0                0   

   Traffic_Signal  Turning_Loop  Sunrise_Sunset  Civil_Twilight  \
0               1             0               1               0   
1               0             0               0               0   
2               0             0               0               0   
3               0             0               0               0   
4               0             0               0               0   

   Nautical_Twilight  Astronomical_Twilight  tempClusters  
0                  0                      0     -0.011049  
1                  0                      0      1.473246  
2                  0                      0      1.613054  
3                  0                      0      1.489703  
4                  0                      0      1.357445  

[5 rows x 24 columns]

In [4]:
#data = data.drop('TimeTaken',axis=1)
xtrain, xtest, ytrain, ytest = train_test_split(
    data.drop('Severity',axis=1),
    data.Severity,
    test_size=0.2
)

In [5]:
le = LabelEncoder()
le.fit(ytrain.ravel())

LabelEncoder()

In [6]:
ytrain =pd.DataFrame(le.transform(ytrain))
ytest = pd.DataFrame(le.transform(ytest))

In [7]:
xgb = XGBClassifier(n_jobs=-1)

In [8]:
xgb.fit(xtrain, ytrain)
trianpred = xgb.predict(xtrain)

/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:299: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:301: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:332: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:323: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. U

In [10]:
metrics(ytrain, trianpred)

[[   138    857    124      0]
 [     3 280079  11237    624]
 [     1  18025  52314    205]
 [     0   8427    581   3602]]
the accuracy is  0.8934551070259983
              precision    recall  f1-score   support

           0       0.97      0.12      0.22      1119
           1       0.91      0.96      0.93    291943
           2       0.81      0.74      0.78     70545
           3       0.81      0.29      0.42     12610

    accuracy                           0.89    376217
   macro avg       0.88      0.53      0.59    376217
weighted avg       0.89      0.89      0.89    376217


0.8934551070259983

In [11]:
ypred = xgb.predict(xtest)
metrics(ytest, ypred)

[[   12   246    32     0]
 [    0 69766  2970   248]
 [    0  4758 12845    64]
 [    0  2290   132   692]]
the accuracy is  0.8858114932752114
              precision    recall  f1-score   support

           0       1.00      0.04      0.08       290
           1       0.91      0.96      0.93     72984
           2       0.80      0.73      0.76     17667
           3       0.69      0.22      0.34      3114

    accuracy                           0.89     94055
   macro avg       0.85      0.49      0.53     94055
weighted avg       0.88      0.89      0.88     94055


/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:299: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(dtype):
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:301: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  elif is_categorical_dtype(dtype) and enable_categorical:
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:332: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. Use isinstance(dtype, CategoricalDtype) instead
  if is_categorical_dtype(dtype)
/Users/manedge/miniconda/envs/EnvironmentTest/lib/python3.11/site-packages/xgboost/data.py:323: FutureWarning: is_categorical_dtype is deprecated and will be removed in a future version. U

0.8858114932752114